version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
  back:
    build: ./backend
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - ./backend/.:/hack/docker_rails
    ports:
      - "5000:5000"
    links:
      - db
  front:
    build: ./frontend
    command: npm run dev 
    volumes:
      - ./frontend/.:/hack/docker_nuxt
    ports:
      - "3000:3000"
      ##違うコンテナが立ち上がるからコンテナのディレクトリは分けなくていい



